<?php

namespace AppBundle\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAvailableRooms($date_start='1900-01-01', $date_final='2100-01-01')
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		
		//query rooms that do have reservations  
		$query_room_ids = $em->createQuery("
					SELECT IDENTITY(b.room) FROM AppBundle:Reservation b
					WHERE NOT (b.dateOut  <'$date_start'
						OR
						b.dateIn > '$date_final'
					)
				");
		$dql_query_room_ids= $query_room_ids->getDQL();
		$qb->resetDQLParts();
		
		//query room that do not have reservations
		$room_array= $qb->select('r')
					->from('AppBundle:Room', 'r')
					->where($qb->expr()->notIn('r.id', $dql_query_room_ids))
					->getQuery()
					->getResult();
		
		try {
			
			return $room_array;
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
		return [];
	}
	
	public function checkRoomAvailability($room_id, $date_start, $date_final)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		
		
		$qb = $em->createQueryBuilder();
		
		$nots = $em->createQuery("
				SELECT COUNT(b) FROM AppBundle:Reservation b
				WHERE NOT (b.dateOut   < '$date_start'
				OR
				b.dateIn > '$date_final')
				AND b.room = $room_id
				
				")->getSingleScalarResult();
		
		try {
			
			return $nots;
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

}
